name: CI-CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Give permission to Jest
        run: chmod +x ./node_modules/.bin/jest
      
      - name: Verify if all files are of type css/html/js/ts
        run: |
          # Verifica arquivos com extensões diferentes de html, css, js, ts
          invalid_files=$(find . -type f ! \( -iname "*.html" -o -iname "*.css" -o -iname "*.js" -o -iname "*.ts" \))
          if [ -n "$invalid_files" ]; then
            echo "Arquivos inválidos encontrados: $invalid_files"
            exit 1
          else
            echo "Todos os arquivos têm extensões permitidas."
          fi

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
      - name: Deploy to production
        run: echo "Deploying to production environment"
